apps/about/urls.py
from django.urls import path
from .views import about
app_name='about'

urlpatterns = [
      path('',about,name='about'),
]

apps/blog/urls.py
from django.urls import path
from .views import blog
app_name='blog'

urlpatterns = [
      path('',blog,name='blog'),
]

apps/hotels/urls.py
from django.urls import path
from .views import hotel,hotel_filter,hotel_detail,hotel_room_detail
app_name='hotel'

urlpatterns = [
      path('',hotel,name='hotel'),
      path('<int:pk>/',hotel_detail,name='hotel-detail'),
      path('<int:pk>/<int:pk_>',hotel_room_detail,name='hotel-room-detail'),
      path('filter/',hotel_filter,name='hotel-filter'),  # type: ignore
]

apps/tours/urls.py
from django.urls import path
from .views import tour,tour_single
app_name='tour'

urlpatterns = [
      path('',tour,name='tour'),
      path('<int:pk>/',tour_single,name='tour-single'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('profile/',include('apps.profiles.urls' , namespace='profiles')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('tour/', include('apps.tours.urls', namespace='tour')),
    path('service/', include('apps.services.urls', namespace='services')),
    path('contact/', include('apps.contact.urls', namespace='contact')),
    path('hotel/', include('apps.hotels.urls', namespace='hotels')),
    path('about/', include('apps.about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/about/models.py
from django.db import models

# Create your models here.

apps/blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title



class Tag(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title

def path_to_blog_image(instance,filename):
      title=instance.title
      category=instance.category
      return 'blog/{0}/{1}/images/{2}'.format(category, title, filename)

class Blog(models.Model):
      title = models.CharField(max_length=255)
      image = models.ImageField(upload_to=path_to_blog_image)
      content = RichTextField()
      category = models.ForeignKey(Category, on_delete=models.CASCADE)
      tag = models.ManyToManyField(Tag)
      created = models.DateTimeField(auto_now_add=True)

      def __str__(self):
            return self.title

apps/contact/models.py
from django.db import models

# Create your models here.

apps/hotels/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.db.models.signals import post_save, pre_save
# Create your models here.


class HotelCategory(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Room(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='hotels',null=True)
    price = models.IntegerField()
    check_in=models.DateField(null=True)
    check_out=models.DateField(null=True)
    cat=models.CharField(max_length=255 ,null=True)
    empty=models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return self.title


class Tour(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Facility(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


def path_to_hotel_image(instance, filename):
    category = instance.hotel_cat.title
    tour = instance.tour
    name = instance.name
    return 'hotels/{0}/{1}/{2}images/{3}'.format(tour, category, name, filename)


class Hotel(models.Model):
    name = models.CharField(max_length=255)
    hotel_cat = models.ForeignKey(HotelCategory, on_delete=models.CASCADE, related_name='hotel_cat')
    image = models.ImageField(upload_to=path_to_hotel_image)
    rooms= models.ManyToManyField(Room)
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)
    facilities = models.ManyToManyField(Facility)
    description = RichTextField()
    stars = models.IntegerField(null=True,blank=True,default=3)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class HotelRank(models.Model):
    user=models.ForeignKey('auth.User',null=True,on_delete=models.CASCADE)
    stars = models.IntegerField()
    hotel = models.ForeignKey(Hotel, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.hotel}->{self.stars}'


# def hotel_star_post_save(instance, sender, created, *args, **kwargs):
#     if created:
#         hotel_stars = HotelRank.objects.filter(hotel_id=instance.id)
#         a = 0
#         for i in hotel_stars:
#             a += i.stars

#         instance.stars =a/len(hotel_stars)
#         instance.save()

# post_save.connect(hotel_star_post_save, sender=Hotel)

apps/services/models.py
from django.db import models

# Create your models here
class Cat(models.Model):
      title = models.CharField(max_length=255)

      def __str__(self):
            return self.title
class Car(models.Model):
      name=models.CharField(max_length=255)
      cat=models.ForeignKey(Cat, null=True,on_delete=models.CASCADE)
      empty = models.BooleanField(default=False)

class Rent(models.Model):
      car=models.ForeignKey(Car, null=True, on_delete=models.CASCADE)
      where=models.CharField(max_length=255)
      start=models.DateField()
      end=models.DateField()
      price=models.IntegerField()

      def __str__(self):
            return self.car

apps/tours/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.html import escape
# Create your models here.
class TravelTourDestinationImages(models.Model):
      image=models.ImageField()
      

      
      # def image_tag(self):
      #       return u'<img src="%s" />' % escape(self.image.url)
      # image_tag.short_description = 'TravelTourDestinationImages'
      # image_tag.allow_tags = True
      
class TravelTourDestination(models.Model):
      title = models.CharField(max_length=25)
      content=RichTextField()
      images = models.ManyToManyField(TravelTourDestinationImages)

      def __str__(self):
            return self.title

class TravelCategory(models.Model):
      title = models.CharField(max_length=25, blank=True)

      def __str__(self):
            return self.title


class Travel(models.Model):
      title = models.CharField(max_length=255 )
      location=models.CharField(max_length=255)
      image=models.ImageField(null=True)
      travel_destination=models.ManyToManyField(TravelTourDestination)
      cat=models.ManyToManyField(TravelCategory)
      stars=models.IntegerField(default=3)
      price=models.IntegerField(default=300)
      created_at=models.DateTimeField(auto_now_add=True)

      def __str__(self):
            return self.title


class TravelRank(models.Model):
    user=models.ForeignKey('auth.User',null=True,on_delete=models.CASCADE)
    stars = models.IntegerField()
    travel = models.ForeignKey(Travel, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.travel}->{self.stars}'

apps/about/views.py
from django.shortcuts import render

# Create your views here.
def about(request):
      return render(request, 'about.html')

apps/blog/views.py
from django.shortcuts import render

# Create your views here.
def blog(request):
      return render(request, 'blog.html')

apps/contact/views.py
from django.shortcuts import render

# Create your views here.
def contact(request):
      return render(request, 'contact.html')

apps/hotels/views.py
from django.shortcuts import render,redirect
from .models import Hotel,HotelCategory, Room,Tour
from django.http import JsonResponse
from apps.profiles.models import MyHotel
from django.core.paginator import Paginator
from datetime import datetime,date
from django.db.models import Q

# Create your views here.


def hotel(request):
      hotels=Hotel.objects.all()
      stars_=request.POST.getlist('stars')  #requestdan kelgan stars
      hotel_cats_=request.POST.getlist('cats')
      locations=request.POST.getlist('locations') 
      facilities=request.POST.getlist('facilities')
      # not_filter_hotels=Hotel.objects.all()
      _stars=[int(i) for i in stars_]
      
      if _stars:
            hotels=hotels.filter(stars__in=_stars)
            
      if hotel_cats_:
            hotel_cat=Hotel.objects.none()
            for i in hotel_cats_:
                  hotel_cat=hotel_cat.union(Hotel.objects.filter(hotel_cat__title=i))
            hotels=hotels.intersection(hotel_cat)
      
      if locations:
            hotel_locations=Hotel.objects.none()
            for i in locations:
                  hotel_locations=hotel_locations.union(Hotel.objects.filter(tour__title=i))
            hotels=hotels.intersection(hotel_locations)
  



      context={
            'hotels':hotels,
            'cats':HotelCategory.objects.all(),
            'tours':Tour.objects.all(),
            'stars':stars_,
            'hotel_cats_':hotel_cats_,
            'locations':locations,

      }
      return render(request, 'hotel.html',context)

def hotel_detail(request,pk):

      hotel = Hotel.objects.get(id=pk)
      rooms=hotel.rooms.all()
      # rooms=rooms.filter(datetime.date(2009,8,22))

      cat=request.GET.get('cat')
      if request.method == 'POST':
            check_in=request.POST.get('check_in')
            check_out=request.POST.get('check_out')
            room=rooms.filter(~Q(check_out__range=[check_in,check_out]) , ~Q(check_in__range=[check_in,check_out]))
            
            rooms=room
                                      
      if cat!=None:
            rooms = rooms.filter(cat__exact=cat)
      p=Paginator(rooms,12)
      page=request.GET.get('page') 
      posts_ = p.get_page(page)


      

      return render(request, 'hotels.html',{'hotel':hotel,'rooms':posts_})

def hotel_filter(request):
      hotels=Hotel.objects.all()

      sid=request.POST.get('_cid')

      if sid:
            hotels=Hotel.objects.filter(stars=int(sid))
      context={
            'hotels':hotels,}
      return render(request, 'hotel.html',context)    


def hotel_room_detail(request,pk,pk_):
      if request.method == 'POST':
            buy_room=MyHotel(profile=request.user.profile,hotels_id=pk,rooms_id=pk_)
            if buy_room not in MyHotel.objects.filter(profile_id=request.user.profile.id):
               buy_room.save()
               get_room=Room.objects.get(id=pk_)
               get_room.empty=True
               get_room.save()
               return redirect(f'/hotel/{pk}/')
      
            


      room=Room.objects.get(id=pk_)


      return render(request, 'room.html',{'room':room})
      

apps/services/views.py
from django.shortcuts import render,redirect
from .models import Car,Rent

def service(request):
      print(request.POST.get('where'))
      return render(request, 'services.html')

apps/tours/views.py
from django.shortcuts import render
from .models import Travel
from apps.profiles.models import MyTravel
# Create your views here.

def tour(request):
      travels=Travel.objects.all()
      locations={}
      for i,k in enumerate(travels):
            if k.location not in locations.values():
                  locations[i]=k.location
      context={
            'travels':travels,
            'locations':locations,
      }
      return render(request, 'tours.html',context)


def tour_single(request,pk=None):
      
      travel=Travel.objects.get(id=pk)
      if request.method == 'POST':
            
            get_ratel=MyTravel(profile=request.user.profile,travel_id=pk)
            get_ratel.save()

      context={
            'travel':travel,
      }
      return render(request,'tour-place.html',context)

templates/about.html
{% extends 'base.html' %}
{% block content %}
  

    <aside id="colorlib-hero">
      <div class="flexslider">
        <ul class="slides">
          <li style="background-image: url(images/cover-img-5.jpg);">
            <div class="overlay"></div>
            <div class="container-fluid">
              <div class="row">
                <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 slider-text">
                  <div class="slider-text-inner text-center">
                    <h2>by colorlib.com</h2>
                    <h1>About us</h1>
                  </div>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </aside>
    <div id="colorlib-about">
      <div class="container">
        <div class="row">
          <div class="about-flex">
            <div class="col-one-forth aside-stretch animate-box">
              <div class="row">
                <div class="col-md-12 about">
                  <h2>About</h2>
                  <ul>
                    <li><a href="#">History</a></li>
                    <li><a href="#">Staff</a></li>
                    <li><a href="#">Connect with us</a></li>
                    <li><a href="#">Faqs</a></li>
                    <li><a href="#">Career</a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-three-forth animate-box">
              <h2>History</h2>
              <div class="row">
                <div class="col-md-12">
                  <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live
                    the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large
                    language ocean.</p>
                  <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is
                    a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                  <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic
                    life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the
                    far World of Grammar.</p>
                  <div class="row row-pb-sm">
                    <div class="col-md-6">
                      <img class="img-responsive" src="images/xhotel-7.jpg.pagespeed.ic.IHkuFDjjUD.jpg" alt="">
                    </div>
                    <div class="col-md-6">
                      <p>The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild
                        Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her
                        seven versalia, put her initial into the belt and made herself on the way.</p>
                      <p>When she reached the first hills of the Italic Mountains, she had a last view back on the
                        skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her
                        own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her
                        way.</p>
                    </div>
                  </div>
                  <p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline
                    of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road,
                    the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way.</p>
                  <p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would
                    have been rewritten a thousand times and everything that was left from its origin would be the word
                    "and" and the Little Blind Text should turn around and return to its own, safe country.</p>
                  <p>But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy
                    Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where
                    they abused her for their.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="colorlib-testimony" class="colorlib-light-grey">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center colorlib-heading animate-box">
            <h2>Our Satisfied Guests says</h2>
            <p>We love to tell our successful far far away, behind the word mountains, far from the countries Vokalia
              and Consonantia, there live the blind texts.</p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 col-md-offset-2 animate-box">
            <div class="owl-carousel2">
              <div class="item">
                <div class="testimony text-center">
                  <span class="img-user" style="background-image:url(images/person1.jpg)"></span>
                  <span class="user">Alysha Myers</span>
                  <small>Miami Florida, USA</small>
                  <blockquote>
                    <p>" A small river named Duden flows by their place and supplies it with the necessary regelialia.
                    </p>
                  </blockquote>
                </div>
              </div>
              <div class="item">
                <div class="testimony text-center">
                  <span class="img-user"
                    style="background-image:url(images/xperson2.jpg.pagespeed.ic.XbL2j5Z0LG.jpg)"></span>
                  <span class="user">James Fisher</span>
                  <small>New York, USA</small>
                  <blockquote>
                    <p>One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the
                      far World of Grammar.</p>
                  </blockquote>
                </div>
              </div>
              <div class="item">
                <div class="testimony text-center">
                  <span class="img-user"
                    style="background-image:url(images/xperson3.jpg.pagespeed.ic.h5rIOYQyrQ.jpg)"></span>
                  <span class="user">Jacob Webb</span>
                  <small>Athens, Greece</small>
                  <blockquote>
                    <p>Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran
                      over her cheek, then she continued her way.</p>
                  </blockquote>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="colorlib-subscribe" style="background-image:url(images/ximg_bg_2.jpg.pagespeed.ic.kmgRidfqii.jpg)"
      data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center colorlib-heading animate-box">
            <h2>Sign Up for a Newsletter</h2>
            <p>Sign up for our mailing list to get latest updates and offers.</p>
            <form class="form-inline qbstp-header-subscribe">
              <div class="row">
                <div class="col-md-12 col-md-offset-0">
                  <div class="form-group">
                    <input type="text" class="form-control" id="email" placeholder="Enter your email">
                    <button type="submit" class="btn btn-primary">Subscribe</button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% endblock content %}

templates/contact.html
{% extends 'base.html' %}
{% block content %}

<aside id="colorlib-hero">
  <div class="flexslider">
    <ul class="slides">
      <li style="background-image:url(images/xcover-img-3.jpg.pagespeed.ic.sVsUWPCiGf.jpg)">
        <div class="overlay"></div>
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 slider-text">
              <div class="slider-text-inner text-center">
                <h2>by colorlib.com</h2>
                <h1>Contact us</h1>
              </div>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>
</aside>
<div id="colorlib-contact">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1 animate-box">
        <h3>Get In Touch</h3>
        <form action="#">
          <div class="row form-group">
            <div class="col-md-6 padding-bottom">
              <label for="fname">First Name</label>
              <input type="text" id="fname" class="form-control" placeholder="Your firstname">
            </div>
            <div class="col-md-6">
              <label for="lname">Last Name</label>
              <input type="text" id="lname" class="form-control" placeholder="Your lastname">
            </div>
          </div>
          <div class="row form-group">
            <div class="col-md-12">
              <label for="email">Email</label>
              <input type="text" id="email" class="form-control" placeholder="Your email address">
            </div>
          </div>
          <div class="row form-group">
            <div class="col-md-12">
              <label for="subject">Subject</label>
              <input type="text" id="subject" class="form-control" placeholder="Your subject of this message">
            </div>
          </div>
          <div class="row form-group">
            <div class="col-md-12">
              <label for="message">Message</label>
              <textarea name="message" id="message" cols="30" rows="10" class="form-control"
                placeholder="Say something about us"></textarea>
            </div>
          </div>
          <div class="form-group text-center">
            <input type="submit" value="Send Message" class="btn btn-primary">
          </div>
        </form>
      </div>
      <div class="col-md-10 col-md-offset-1 animate-box">
        <h3>Contact Information</h3>
        <div class="row contact-info-wrap">
          <div class="col-md-3">
            <p><span><i class="icon-location"></i></span> 198 West 21th Street, <br> Suite 721 New York NY 10016</p>
          </div>
          <div class="col-md-3">
            <p><span><i class="icon-phone3"></i></span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
          </div>
          <div class="col-md-3">
            <p><span><i class="icon-paperplane"></i></span> <a
                href="https://preview.colorlib.com/cdn-cgi/l/email-protection#5d34333b321d2432282f2e342938733e3230"><span
                  class="__cf_email__"
                  data-cfemail="a8c1c6cec7e8d1c7dddadbc1dccd86cbc7c5">[email&#160;protected]</span></a></p>
          </div>
          <div class="col-md-3">
            <p><span><i class="icon-globe"></i></span> <a href="#">yoursite.com</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="map" class="colorlib-map"></div>
<div id="colorlib-subscribe" style="background-image:url(images/ximg_bg_2.jpg.pagespeed.ic.kmgRidfqii.jpg)"
  data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center colorlib-heading animate-box">
        <h2>Sign Up for a Newsletter</h2>
        <p>Sign up for our mailing list to get latest updates and offers.</p>
        <form class="form-inline qbstp-header-subscribe">
          <div class="row">
            <div class="col-md-12 col-md-offset-0">
              <div class="form-group">
                <input type="text" class="form-control" id="email" placeholder="Enter your email">
                <button type="submit" class="btn btn-primary">Subscribe</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/hotels.html
{% extends "base.html" %}
{% block content %}

<aside id="colorlib-hero">
  <div class="flexslider">
    <ul class="slides">
      <li style="background-image:url({{hotel.image.url}})">
        <div class="overlay"></div>
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 slider-text">
              <div class="slider-text-inner text-center">
                <h1>{{hotel.name}}</h1>
              </div>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>
</aside>
<div class="colorlib-wrap">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="row">
          <div class="wrap-division">

            {% for i in rooms %}
            <div class="col-md-6 col-sm-6 animate-box">
              <div class="hotel-entry">
                <a href="{% url 'hotel:hotel-room-detail' hotel.id i.id  %}" class="hotel-img"
                  style="background-image:url({{i.image.url}})">
                  <p class="price"><span>${{i.price}}</span><small> /night</small></p>
                </a>
                <div class="desc">
                  <p class="star">{{i.cat}}</p>
                  <h3><a href="hotel-room.html">{{i.title}}</a></h3>
                  <span class="place">{{hotel.tour}}</span>
                  <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.
                  </p>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="row mb-5">
          <div class="col-md-12 text-center">
              <div class="block-27">
                  <ul class="pagination">
                      {% if rooms.has_previous %}
                      <li class="page-item  active"><a class="page-link"
                              href="?page={{ rooms.previous_page_number }}">Prev</a>
                      </li>
                      {% endif %}
                      {% for i in p.page_range %}
                      {% if rooms.number == i %}
                      <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                      {% else %}
                      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>

                      {% endif %}

                      {% endfor %}
                      {% if rooms.has_next %}
                      <li class="page-item  active"><a class="page-link"
                              href="?page={{ posts.next_page_number }}">Next</a>
                      </li>
                      {% endif %}
                  </ul>
              </div>
          </div>
      </div>
      </div>

      <div class="col-md-3">
        <div class="sidebar-wrap">
          <div class="side search-wrap animate-box">
            <h3 class="sidebar-heading">Find your hotel</h3>
            <form method="post" class="colorlib-form">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label for="date">Check-in:</label>
                    <div class="form-field">
                      <i class="icon icon-calendar2"></i>
                      <input type="date"  name='check_in' class="form-control" placeholder="Check-in date">
                    </div>
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
                    <label for="date">Check-out:</label>
                    <div class="form-field">
                      <i class="icon icon-calendar2"></i>
                      <input type="date"  name='check_out' class="form-control" placeholder="Check-out date">
                    </div>
                  </div>
                </div>
               
                <div class="col-md-12">
                  <input type="submit" name="submit" id="submit" value="Find Hotel" class="btn btn-primary btn-block">
                </div>
              </div>
            </form>
          </div>
          <div class="side animate-box">
            <div class="row">
              <div class="col-md-12">
                <h3 class="sidebar-heading">Categories</h3>
                <a href="/hotel/{{hotel.id}}/?cat=premium">Premium</a>
                <br>
                <a href="/hotel/{{hotel.id}}/?cat=middle">Middle</a>
                <br> <a href="/hotel/{{hotel.id}}/?cat=cheap">Cheap</a><br>
                <a href="/hotel/{{hotel.id}}/">All</a>

              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>
<div id="colorlib-subscribe" style="background-image:url(images/ximg_bg_2.jpg.pagespeed.ic.kmgRidfqii.jpg)"
  data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center colorlib-heading animate-box">
        <h2>Sign Up for a Newsletter</h2>
        <p>Sign up for our mailing list to get latest updates and offers.</p>
        <form class="form-inline qbstp-header-subscribe">
          <div class="row">
            <div class="col-md-12 col-md-offset-0">
              <div class="form-group">
                <input type="text" class="form-control" id="email" placeholder="Enter your email">
                <button type="submit" class="btn btn-primary">Subscribe</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/room.html
{% extends 'base.html' %}

{% block content %}
<aside id="colorlib-hero">
      <div class="flexslider">
            <ul class="slides">
                  <li style="background-image:url({{room.image.url}})">
                        <div class="overlay"></div>
                        <div class="container-fluid">
                              <div class="row">
                                    <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 slider-text">
                                          <div class="slider-text-inner text-center">
                                                <h1>{{hotel.name}}</h1>
                                          </div>
                                    </div>
                              </div>
                        </div>
                  </li>
            </ul>
      </div>
</aside>
<form action="" method="post">
      {% csrf_token %}
<div class="colorlib-wrap">
      <div class="container">
            <h3>${{room.price}}</h3>
            <br>
            <h4>{{room.id}}-room</h4>
            <h4>room's cat {{room.cat}}</h4>
            <button type="submit"> To Buy</button>
      </div>
</div>
</form>
{% endblock content %}